connection:
  type: ssh
  ssh_options:
    user_name: user name on host
    keys:
      - "~/.config/id_rsa"

docker:
  port: 2375

environments:
  staging:
    hosts:
      - host: staging.example.com
        images:
          - organization/imageName:latest
  production:
    hosts:
      - host: example.com
        images:
          - organization/imageName:latest
