connection:
  type: ssh
  ssh_options:
    user_name: user name on host
    keys:
      - "~/.config/id_rsa"

docker:
  port: 2375

environments:
  staging:
    hosts:
      - host: staging.example.com
        images:
          - name: organization/imageName:latest
            port_mappings: 
              - 0.0.0.0:80->80
  production:
    hosts:
      - host: example.com
        images:
          - name: organization/imageName:latest
            port_mappings: 
              - 0.0.0.0:80->80
